// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: question.proto

/*
	Package question is a generated protocol buffer package.

	It is generated from these files:
		question.proto

	It has these top-level messages:
		RspStatus
		IndexRequest
		IndexResponse
		GetUserShareRequest
		GetUserShareResponse
		GetQuestionRequest
		GetQuestionResponse
		QuestionList
*/
package question

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import binary "encoding/binary"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RspStatus struct {
	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *RspStatus) Reset()                    { *m = RspStatus{} }
func (m *RspStatus) String() string            { return proto.CompactTextString(m) }
func (*RspStatus) ProtoMessage()               {}
func (*RspStatus) Descriptor() ([]byte, []int) { return fileDescriptorQuestion, []int{0} }

// index request
type IndexRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (m *IndexRequest) Reset()                    { *m = IndexRequest{} }
func (m *IndexRequest) String() string            { return proto.CompactTextString(m) }
func (*IndexRequest) ProtoMessage()               {}
func (*IndexRequest) Descriptor() ([]byte, []int) { return fileDescriptorQuestion, []int{1} }

// index response
type IndexResponse struct {
	Status     *RspStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Chance     int64      `protobuf:"varint,2,opt,name=chance,proto3" json:"chance"`
	Success    int64      `protobuf:"varint,3,opt,name=success,proto3" json:"success"`
	Score      int64      `protobuf:"varint,4,opt,name=score,proto3" json:"score"`
	RemindList []string   `protobuf:"bytes,5,rep,name=remindList" json:"remindList,omitempty"`
}

func (m *IndexResponse) Reset()                    { *m = IndexResponse{} }
func (m *IndexResponse) String() string            { return proto.CompactTextString(m) }
func (*IndexResponse) ProtoMessage()               {}
func (*IndexResponse) Descriptor() ([]byte, []int) { return fileDescriptorQuestion, []int{2} }

// user_share request
type GetUserShareRequest struct {
	EncryptedData string `protobuf:"bytes,1,opt,name=encryptedData,proto3" json:"encryptedData,omitempty"`
	Iv            string `protobuf:"bytes,2,opt,name=iv,proto3" json:"iv,omitempty"`
	UserId        int64  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (m *GetUserShareRequest) Reset()                    { *m = GetUserShareRequest{} }
func (m *GetUserShareRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserShareRequest) ProtoMessage()               {}
func (*GetUserShareRequest) Descriptor() ([]byte, []int) { return fileDescriptorQuestion, []int{3} }

// user_share response
type GetUserShareResponse struct {
	Status      *RspStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Chance      int64      `protobuf:"varint,2,opt,name=chance,proto3" json:"chance"`
	Repeat      int64      `protobuf:"varint,3,opt,name=repeat,proto3" json:"repeat"`
	TodayShares int64      `protobuf:"varint,4,opt,name=today_shares,json=todayShares,proto3" json:"today_shares"`
	ErrorCode   int64      `protobuf:"varint,5,opt,name=error_code,json=errorCode,proto3" json:"error_code"`
}

func (m *GetUserShareResponse) Reset()                    { *m = GetUserShareResponse{} }
func (m *GetUserShareResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserShareResponse) ProtoMessage()               {}
func (*GetUserShareResponse) Descriptor() ([]byte, []int) { return fileDescriptorQuestion, []int{4} }

//  question request
type GetQuestionRequest struct {
	Sign   string `protobuf:"bytes,1,opt,name=sign,proto3" json:"sign,omitempty"`
	UserId int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (m *GetQuestionRequest) Reset()                    { *m = GetQuestionRequest{} }
func (m *GetQuestionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetQuestionRequest) ProtoMessage()               {}
func (*GetQuestionRequest) Descriptor() ([]byte, []int) { return fileDescriptorQuestion, []int{5} }

//  question response
type GetQuestionResponse struct {
	Status *RspStatus      `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Data   []*QuestionList `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
}

func (m *GetQuestionResponse) Reset()                    { *m = GetQuestionResponse{} }
func (m *GetQuestionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetQuestionResponse) ProtoMessage()               {}
func (*GetQuestionResponse) Descriptor() ([]byte, []int) { return fileDescriptorQuestion, []int{6} }

type QuestionList struct {
	Num1     int64   `protobuf:"varint,1,opt,name=num1,proto3" json:"num1"`
	Operator string  `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Num2     int64   `protobuf:"varint,3,opt,name=num2,proto3" json:"num2"`
	Result   int64   `protobuf:"varint,4,opt,name=result,proto3" json:"result"`
	Success  int64   `protobuf:"varint,5,opt,name=success,proto3" json:"success"`
	Seconds  float32 `protobuf:"fixed32,6,opt,name=seconds,proto3" json:"seconds"`
}

func (m *QuestionList) Reset()                    { *m = QuestionList{} }
func (m *QuestionList) String() string            { return proto.CompactTextString(m) }
func (*QuestionList) ProtoMessage()               {}
func (*QuestionList) Descriptor() ([]byte, []int) { return fileDescriptorQuestion, []int{7} }

func init() {
	proto.RegisterType((*RspStatus)(nil), "question.RspStatus")
	proto.RegisterType((*IndexRequest)(nil), "question.IndexRequest")
	proto.RegisterType((*IndexResponse)(nil), "question.IndexResponse")
	proto.RegisterType((*GetUserShareRequest)(nil), "question.GetUserShareRequest")
	proto.RegisterType((*GetUserShareResponse)(nil), "question.GetUserShareResponse")
	proto.RegisterType((*GetQuestionRequest)(nil), "question.GetQuestionRequest")
	proto.RegisterType((*GetQuestionResponse)(nil), "question.GetQuestionResponse")
	proto.RegisterType((*QuestionList)(nil), "question.QuestionList")
}
func (m *RspStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RspStatus) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Code))
	}
	if len(m.Msg) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(len(m.Msg)))
		i += copy(dAtA[i:], m.Msg)
	}
	return i, nil
}

func (m *IndexRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndexRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.UserId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.UserId))
	}
	return i, nil
}

func (m *IndexResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndexResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Status.Size()))
		n1, err := m.Status.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Chance != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Chance))
	}
	if m.Success != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Success))
	}
	if m.Score != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Score))
	}
	if len(m.RemindList) > 0 {
		for _, s := range m.RemindList {
			dAtA[i] = 0x2a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *GetUserShareRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetUserShareRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.EncryptedData) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(len(m.EncryptedData)))
		i += copy(dAtA[i:], m.EncryptedData)
	}
	if len(m.Iv) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(len(m.Iv)))
		i += copy(dAtA[i:], m.Iv)
	}
	if m.UserId != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.UserId))
	}
	return i, nil
}

func (m *GetUserShareResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetUserShareResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Status.Size()))
		n2, err := m.Status.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.Chance != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Chance))
	}
	if m.Repeat != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Repeat))
	}
	if m.TodayShares != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.TodayShares))
	}
	if m.ErrorCode != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.ErrorCode))
	}
	return i, nil
}

func (m *GetQuestionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetQuestionRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Sign) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(len(m.Sign)))
		i += copy(dAtA[i:], m.Sign)
	}
	if m.UserId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.UserId))
	}
	return i, nil
}

func (m *GetQuestionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetQuestionResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Status.Size()))
		n3, err := m.Status.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if len(m.Data) > 0 {
		for _, msg := range m.Data {
			dAtA[i] = 0x12
			i++
			i = encodeVarintQuestion(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *QuestionList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuestionList) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Num1 != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Num1))
	}
	if len(m.Operator) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(len(m.Operator)))
		i += copy(dAtA[i:], m.Operator)
	}
	if m.Num2 != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Num2))
	}
	if m.Result != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Result))
	}
	if m.Success != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintQuestion(dAtA, i, uint64(m.Success))
	}
	if m.Seconds != 0 {
		dAtA[i] = 0x35
		i++
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Seconds))))
		i += 4
	}
	return i, nil
}

func encodeVarintQuestion(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedRspStatus(r randyQuestion, easy bool) *RspStatus {
	this := &RspStatus{}
	this.Code = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Code *= -1
	}
	this.Msg = string(randStringQuestion(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedIndexRequest(r randyQuestion, easy bool) *IndexRequest {
	this := &IndexRequest{}
	this.UserId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.UserId *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedIndexResponse(r randyQuestion, easy bool) *IndexResponse {
	this := &IndexResponse{}
	if r.Intn(10) != 0 {
		this.Status = NewPopulatedRspStatus(r, easy)
	}
	this.Chance = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Chance *= -1
	}
	this.Success = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Success *= -1
	}
	this.Score = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Score *= -1
	}
	v1 := r.Intn(10)
	this.RemindList = make([]string, v1)
	for i := 0; i < v1; i++ {
		this.RemindList[i] = string(randStringQuestion(r))
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetUserShareRequest(r randyQuestion, easy bool) *GetUserShareRequest {
	this := &GetUserShareRequest{}
	this.EncryptedData = string(randStringQuestion(r))
	this.Iv = string(randStringQuestion(r))
	this.UserId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.UserId *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetUserShareResponse(r randyQuestion, easy bool) *GetUserShareResponse {
	this := &GetUserShareResponse{}
	if r.Intn(10) != 0 {
		this.Status = NewPopulatedRspStatus(r, easy)
	}
	this.Chance = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Chance *= -1
	}
	this.Repeat = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Repeat *= -1
	}
	this.TodayShares = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.TodayShares *= -1
	}
	this.ErrorCode = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.ErrorCode *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetQuestionRequest(r randyQuestion, easy bool) *GetQuestionRequest {
	this := &GetQuestionRequest{}
	this.Sign = string(randStringQuestion(r))
	this.UserId = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.UserId *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetQuestionResponse(r randyQuestion, easy bool) *GetQuestionResponse {
	this := &GetQuestionResponse{}
	if r.Intn(10) != 0 {
		this.Status = NewPopulatedRspStatus(r, easy)
	}
	if r.Intn(10) != 0 {
		v2 := r.Intn(5)
		this.Data = make([]*QuestionList, v2)
		for i := 0; i < v2; i++ {
			this.Data[i] = NewPopulatedQuestionList(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedQuestionList(r randyQuestion, easy bool) *QuestionList {
	this := &QuestionList{}
	this.Num1 = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Num1 *= -1
	}
	this.Operator = string(randStringQuestion(r))
	this.Num2 = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Num2 *= -1
	}
	this.Result = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Result *= -1
	}
	this.Success = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Success *= -1
	}
	this.Seconds = float32(r.Float32())
	if r.Intn(2) == 0 {
		this.Seconds *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyQuestion interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneQuestion(r randyQuestion) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringQuestion(r randyQuestion) string {
	v3 := r.Intn(100)
	tmps := make([]rune, v3)
	for i := 0; i < v3; i++ {
		tmps[i] = randUTF8RuneQuestion(r)
	}
	return string(tmps)
}
func randUnrecognizedQuestion(r randyQuestion, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldQuestion(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldQuestion(dAtA []byte, r randyQuestion, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateQuestion(dAtA, uint64(key))
		v4 := r.Int63()
		if r.Intn(2) == 0 {
			v4 *= -1
		}
		dAtA = encodeVarintPopulateQuestion(dAtA, uint64(v4))
	case 1:
		dAtA = encodeVarintPopulateQuestion(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateQuestion(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateQuestion(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateQuestion(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateQuestion(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *RspStatus) Size() (n int) {
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovQuestion(uint64(m.Code))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovQuestion(uint64(l))
	}
	return n
}

func (m *IndexRequest) Size() (n int) {
	var l int
	_ = l
	if m.UserId != 0 {
		n += 1 + sovQuestion(uint64(m.UserId))
	}
	return n
}

func (m *IndexResponse) Size() (n int) {
	var l int
	_ = l
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovQuestion(uint64(l))
	}
	if m.Chance != 0 {
		n += 1 + sovQuestion(uint64(m.Chance))
	}
	if m.Success != 0 {
		n += 1 + sovQuestion(uint64(m.Success))
	}
	if m.Score != 0 {
		n += 1 + sovQuestion(uint64(m.Score))
	}
	if len(m.RemindList) > 0 {
		for _, s := range m.RemindList {
			l = len(s)
			n += 1 + l + sovQuestion(uint64(l))
		}
	}
	return n
}

func (m *GetUserShareRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.EncryptedData)
	if l > 0 {
		n += 1 + l + sovQuestion(uint64(l))
	}
	l = len(m.Iv)
	if l > 0 {
		n += 1 + l + sovQuestion(uint64(l))
	}
	if m.UserId != 0 {
		n += 1 + sovQuestion(uint64(m.UserId))
	}
	return n
}

func (m *GetUserShareResponse) Size() (n int) {
	var l int
	_ = l
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovQuestion(uint64(l))
	}
	if m.Chance != 0 {
		n += 1 + sovQuestion(uint64(m.Chance))
	}
	if m.Repeat != 0 {
		n += 1 + sovQuestion(uint64(m.Repeat))
	}
	if m.TodayShares != 0 {
		n += 1 + sovQuestion(uint64(m.TodayShares))
	}
	if m.ErrorCode != 0 {
		n += 1 + sovQuestion(uint64(m.ErrorCode))
	}
	return n
}

func (m *GetQuestionRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Sign)
	if l > 0 {
		n += 1 + l + sovQuestion(uint64(l))
	}
	if m.UserId != 0 {
		n += 1 + sovQuestion(uint64(m.UserId))
	}
	return n
}

func (m *GetQuestionResponse) Size() (n int) {
	var l int
	_ = l
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovQuestion(uint64(l))
	}
	if len(m.Data) > 0 {
		for _, e := range m.Data {
			l = e.Size()
			n += 1 + l + sovQuestion(uint64(l))
		}
	}
	return n
}

func (m *QuestionList) Size() (n int) {
	var l int
	_ = l
	if m.Num1 != 0 {
		n += 1 + sovQuestion(uint64(m.Num1))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovQuestion(uint64(l))
	}
	if m.Num2 != 0 {
		n += 1 + sovQuestion(uint64(m.Num2))
	}
	if m.Result != 0 {
		n += 1 + sovQuestion(uint64(m.Result))
	}
	if m.Success != 0 {
		n += 1 + sovQuestion(uint64(m.Success))
	}
	if m.Seconds != 0 {
		n += 5
	}
	return n
}

func sovQuestion(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozQuestion(x uint64) (n int) {
	return sovQuestion(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RspStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuestion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RspStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RspStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuestion
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuestion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuestion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IndexRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuestion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndexRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndexRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuestion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuestion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IndexResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuestion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndexResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndexResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuestion
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &RspStatus{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chance", wireType)
			}
			m.Chance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Chance |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			m.Success = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Success |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			m.Score = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Score |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemindList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuestion
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemindList = append(m.RemindList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuestion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuestion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetUserShareRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuestion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetUserShareRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetUserShareRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuestion
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Iv", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuestion
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Iv = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuestion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuestion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetUserShareResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuestion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetUserShareResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetUserShareResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuestion
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &RspStatus{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chance", wireType)
			}
			m.Chance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Chance |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Repeat", wireType)
			}
			m.Repeat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Repeat |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TodayShares", wireType)
			}
			m.TodayShares = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TodayShares |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorCode", wireType)
			}
			m.ErrorCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrorCode |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuestion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuestion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetQuestionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuestion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetQuestionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetQuestionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sign", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuestion
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sign = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuestion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuestion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetQuestionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuestion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetQuestionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetQuestionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuestion
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &RspStatus{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuestion
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data, &QuestionList{})
			if err := m.Data[len(m.Data)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuestion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuestion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuestionList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuestion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuestionList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuestionList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Num1", wireType)
			}
			m.Num1 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Num1 |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuestion
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Num2", wireType)
			}
			m.Num2 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Num2 |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			m.Result = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Result |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			m.Success = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Success |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seconds", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Seconds = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipQuestion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuestion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuestion(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuestion
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuestion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthQuestion
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowQuestion
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipQuestion(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthQuestion = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuestion   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("question.proto", fileDescriptorQuestion) }

var fileDescriptorQuestion = []byte{
	// 620 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xed, 0xc6, 0x49, 0xbe, 0x64, 0x92, 0xf6, 0xab, 0xb6, 0xa8, 0x58, 0x11, 0xd8, 0x91, 0x05,
	0x28, 0x02, 0xb5, 0x15, 0xee, 0x0d, 0x2e, 0xa8, 0x20, 0x55, 0x95, 0x90, 0x80, 0xad, 0x38, 0x57,
	0xae, 0xbd, 0xa4, 0x96, 0x88, 0xd7, 0xec, 0xae, 0x2b, 0xfa, 0x4f, 0xf8, 0x49, 0x3d, 0x72, 0xe4,
	0x64, 0xd1, 0x72, 0xc2, 0x17, 0xae, 0x1c, 0x91, 0xc7, 0xeb, 0xd4, 0xa6, 0x2a, 0x07, 0x24, 0x2e,
	0xd9, 0x99, 0xe7, 0x37, 0xb3, 0x3b, 0x6f, 0x66, 0x02, 0x6b, 0x1f, 0x32, 0xae, 0x74, 0x2c, 0x92,
	0xed, 0x54, 0x0a, 0x2d, 0xe8, 0xa0, 0xf6, 0x27, 0x5b, 0xf3, 0x58, 0x9f, 0x64, 0xc7, 0xdb, 0xa1,
	0x58, 0xec, 0xcc, 0xc5, 0x5c, 0xec, 0x20, 0xe1, 0x38, 0x7b, 0x87, 0x1e, 0x3a, 0x68, 0x55, 0x81,
	0xde, 0x53, 0x18, 0x32, 0x95, 0x1e, 0xea, 0x40, 0x67, 0x8a, 0xde, 0x81, 0x6e, 0x28, 0x22, 0x6e,
	0x93, 0x29, 0x99, 0x59, 0x7b, 0x83, 0x22, 0x77, 0xd1, 0x67, 0xf8, 0x4b, 0xd7, 0xc1, 0x5a, 0xa8,
	0xb9, 0xdd, 0x99, 0x92, 0xd9, 0x90, 0x95, 0xa6, 0xf7, 0x00, 0xc6, 0x07, 0x49, 0xc4, 0x3f, 0x32,
	0x8e, 0xd7, 0xd3, 0x4d, 0xe8, 0x67, 0x8a, 0xcb, 0x83, 0xa8, 0xca, 0xc0, 0x8c, 0xe7, 0x9d, 0x13,
	0x58, 0x35, 0x44, 0x95, 0x8a, 0x44, 0x71, 0xfa, 0x08, 0xfa, 0x0a, 0xef, 0x44, 0xe6, 0xc8, 0xdf,
	0xd8, 0x5e, 0x16, 0xb4, 0x7c, 0x0e, 0x33, 0x14, 0xea, 0x41, 0x3f, 0x3c, 0x09, 0x92, 0x90, 0xe3,
	0xdd, 0xd6, 0x1e, 0x14, 0xb9, 0x6b, 0x10, 0x66, 0x4e, 0x7a, 0x1f, 0xfe, 0x53, 0x59, 0x18, 0x72,
	0xa5, 0x6c, 0x0b, 0x49, 0xa3, 0x22, 0x77, 0x6b, 0x88, 0xd5, 0x06, 0x75, 0xa1, 0xa7, 0x42, 0x21,
	0xb9, 0xdd, 0x45, 0xd2, 0xb0, 0xc8, 0xdd, 0x0a, 0x60, 0xd5, 0x41, 0x1d, 0x00, 0xc9, 0x17, 0x71,
	0x12, 0xbd, 0x8c, 0x95, 0xb6, 0x7b, 0x53, 0x6b, 0x36, 0x64, 0x0d, 0xc4, 0x0b, 0x61, 0x63, 0x9f,
	0xeb, 0xb7, 0x8a, 0xcb, 0xc3, 0x93, 0x40, 0xf2, 0xba, 0xf2, 0x7b, 0xb0, 0xca, 0x93, 0x50, 0x9e,
	0xa5, 0x9a, 0x47, 0x2f, 0x02, 0x1d, 0x60, 0x59, 0x43, 0xd6, 0x06, 0xe9, 0x1a, 0x74, 0xe2, 0x53,
	0x23, 0x60, 0x27, 0x3e, 0x6d, 0xe8, 0x65, 0xb5, 0xf4, 0xfa, 0x41, 0xe0, 0x56, 0xfb, 0x96, 0x7f,
	0x25, 0x9b, 0x07, 0x7d, 0xc9, 0x53, 0x1e, 0x68, 0xa3, 0x1a, 0x72, 0x2a, 0x84, 0x99, 0x93, 0xee,
	0xc2, 0x58, 0x8b, 0x28, 0x38, 0x3b, 0x52, 0xe5, 0x5b, 0x94, 0x91, 0x6e, 0xbd, 0xc8, 0xdd, 0x16,
	0xce, 0x46, 0xe8, 0xe1, 0x83, 0x15, 0xdd, 0x02, 0xe0, 0x52, 0x0a, 0x79, 0x84, 0x03, 0xd5, 0xc3,
	0x90, 0xb5, 0x22, 0x77, 0x1b, 0x28, 0x1b, 0xa2, 0xfd, 0x5c, 0x44, 0xdc, 0x7b, 0x06, 0x74, 0x9f,
	0xeb, 0x37, 0xa6, 0x98, 0x5a, 0x55, 0x0a, 0x5d, 0x15, 0xcf, 0x13, 0x23, 0x26, 0xda, 0x0d, 0xcd,
	0x3a, 0x2d, 0xcd, 0x12, 0x6c, 0xcc, 0x55, 0x86, 0xbf, 0x51, 0xec, 0x21, 0x74, 0xa3, 0xb2, 0x79,
	0x9d, 0xa9, 0x35, 0x1b, 0xf9, 0x9b, 0x57, 0xd4, 0x3a, 0x6d, 0x39, 0x02, 0x0c, 0x39, 0xde, 0x17,
	0x02, 0xe3, 0x26, 0x5c, 0x2e, 0x4f, 0x92, 0x2d, 0x1e, 0x37, 0x97, 0xa7, 0xf4, 0x19, 0xfe, 0xd2,
	0x09, 0x0c, 0x44, 0xca, 0x65, 0xa0, 0x85, 0x34, 0x03, 0xb0, 0xf4, 0x4d, 0xa4, 0x6f, 0x5a, 0x50,
	0x47, 0xfa, 0x18, 0xe9, 0x57, 0x2d, 0x52, 0xd9, 0x7b, 0x6d, 0x84, 0x37, 0x2d, 0x2a, 0x11, 0x66,
	0xce, 0xe6, 0xf4, 0xf7, 0xfe, 0x30, 0xfd, 0x25, 0x8d, 0x87, 0x22, 0x89, 0x94, 0xdd, 0x9f, 0x92,
	0x59, 0xc7, 0xd0, 0x2a, 0x88, 0xd5, 0x86, 0xff, 0x9d, 0xc0, 0xa0, 0x2e, 0x8d, 0x3e, 0x81, 0x1e,
	0xae, 0x2e, 0x6d, 0xc8, 0xd1, 0x5c, 0xfa, 0xc9, 0xed, 0x6b, 0x78, 0x25, 0xbd, 0xb7, 0x42, 0x5f,
	0xc3, 0xff, 0x8d, 0x9e, 0x54, 0x2a, 0x5d, 0xb1, 0xaf, 0x37, 0x7c, 0x72, 0xf7, 0x86, 0xaf, 0xcb,
	0x8c, 0xaf, 0x60, 0xdc, 0x5c, 0x0c, 0xda, 0x0e, 0xf8, 0x7d, 0x2d, 0x27, 0xce, 0x4d, 0x9f, 0xeb,
	0x84, 0x7b, 0xf6, 0xf9, 0x85, 0xb3, 0xf2, 0xf3, 0xc2, 0x21, 0xe7, 0x97, 0x0e, 0xf9, 0x7c, 0xe9,
	0x90, 0xaf, 0x97, 0x0e, 0xf9, 0xf4, 0xcd, 0x59, 0x39, 0xee, 0xe3, 0x1f, 0xe4, 0xee, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe1, 0x4e, 0x87, 0xf7, 0x6b, 0x05, 0x00, 0x00,
}
